spring:
    application:
        name: ExploreBG

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
        url: jdbc:mysql://localhost:3306/explore-bg?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

    jpa:
#        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        defer-datasource-initialization: true
#        show-sql: true
#        properties:
#            hibernate:
#                generate_statistics: true

    sql:
        init:
            mode: always

#logging:
#    level:
#        org:
##            springframework:
##                jdbc: DEBUG
#            hibernate:
##                 stat: DEBUG
#                 SQL: DEBUG
#                 type:
#                    descriptor: TRACE